version: "3.8"

services: 
  app: 
    build: 
      target: dev      
      context: .
      args:
        NODE_VERSION: 16
        ALPINE_VERSION: 3.14
    environment:
      PORT: 8080
      NODE_ENV: development
    volumes:
      - ./:/app
    command: sh -c "yarn install && yarn dev"
    tty: true
    ports: 
      - 8080:8080
    networks: 
      - app

  rabbitmq:
    image: rabbitmq:3.8.25-management-alpine
    tty: true
    restart: always
    volumes:
      - rabbitmqData:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 15672:15672
      - 5672:5672
    networks: 
      - app
      
networks: 
  app: {}

volumes:
  rabbitmqData: 
    