const RABBITMQ_TYPE_DIRECT = 'direct';
const RABBITMQ_TYPE_TOPIC = 'topic';
const RABBITMQ_TYPE_FANOUT = 'fanout';
const RABBITMQ_TYPE_HEADERS = 'headers';

const EXCHANGE_EXAMPLE = 'example2_ex';
const EXCHANGE_DL_EXAMPLE = 'example_dl_ex';
const QUEUE_EXAMPLE = 'example2_q';
const QUEUE_DL_EXAMPLE = 'example_dl_q';
const DL_MESSAGE_TTL = 300000; // 5 min
const QUEUE_EXAMPLE_ROUTING_KEY = 'routing_key';
const CONSUMER_MAX_RETRY = 5;

module.exports = {
  EXCHANGE_EXAMPLE,
  EXCHANGE_DL_EXAMPLE,
  QUEUE_EXAMPLE,
  QUEUE_DL_EXAMPLE,
  RABBITMQ_TYPE_DIRECT,
  RABBITMQ_TYPE_TOPIC,
  RABBITMQ_TYPE_FANOUT,
  RABBITMQ_TYPE_HEADERS,
  DL_MESSAGE_TTL,
  QUEUE_EXAMPLE_ROUTING_KEY,
  CONSUMER_MAX_RETRY,
};
